# Generated by Django 3.2.8 on 2022-04-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.CharField(default='resume', max_length=255),
            preserve_default=False,
        ),
    ]
