# Generated by Django 4.0.4 on 2022-04-19 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_body_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='resume',
            new_name='summary',
        ),
    ]
