# Generated by Django 4.0.4 on 2022-06-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content_alter_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
