# Generated by Django 3.2.8 on 2022-04-19 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
    ]
